# Generated by Django 5.2.11 on 2026-02-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
                ('question_key', models.CharField(max_length=80)),
                ('prompt', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('time_limit_seconds', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='scenarios.questiontemplate')),
            ],
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scenarios.scenariotemplate'),
        ),
        migrations.AddConstraint(
            model_name='questiontemplate',
            constraint=models.UniqueConstraint(fields=('scenario', 'question_key'), name='unique_question_key_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='questiontemplate',
            constraint=models.UniqueConstraint(fields=('scenario', 'stage', 'order'), name='unique_stage_order_per_scenario'),
        ),
    ]
