# Generated by Django 6.0.2 on 2026-03-10 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('ended_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('wrong_limit', models.IntegerField(default=5)),
                ('pressure_level', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
