# Generated by Django 5.2.11 on 2026-02-16 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=80)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='created', max_length=20)),
                ('ended_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('wrong_limit', models.IntegerField(default=5)),
                ('advice_summary', models.TextField(blank=True, default='')),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice_id', models.CharField(max_length=80)),
                ('selected_text', models.CharField(blank=True, default='', max_length=200)),
                ('score_delta', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('client_answer_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gameplay.gamesession')),
                ('question_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='gameplay.questionrun')),
            ],
        ),
        migrations.CreateModel(
            name='StageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prepare', 'Prepare'), ('detect', 'Detect'), ('analyse', 'Analyse'), ('remediate', 'Remediate'), ('post_incident', 'Post-Incident')], max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('done', 'Done')], default='locked', max_length=10)),
                ('stage_score', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='gameplay.gamesession')),
            ],
        ),
        migrations.AddField(
            model_name='questionrun',
            name='stage_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gameplay.stagerun'),
        ),
        migrations.AddConstraint(
            model_name='stagerun',
            constraint=models.UniqueConstraint(fields=('session', 'stage'), name='unique_stage_per_session'),
        ),
        migrations.AddConstraint(
            model_name='stagerun',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='unique_stage_order_per_session'),
        ),
        migrations.AddConstraint(
            model_name='questionrun',
            constraint=models.UniqueConstraint(fields=('stage_run', 'order'), name='unique_question_order_per_stage_run'),
        ),
        migrations.AddConstraint(
            model_name='questionrun',
            constraint=models.UniqueConstraint(fields=('stage_run', 'question_key'), name='unique_question_key_per_stage_run'),
        ),
    ]
