# Generated by Django 5.2.11 on 2026-02-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='advice_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ended_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='wrong_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('session', 'question_id'), name='unique_answer_per_question_per_session'),
        ),
    ]
