# Generated by Django 5.2.11 on 2026-02-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_stage_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
